### ISSUE TITLE
老哥，我启动后，点所有的东西都会变成这样-。直接无法使用

### ISSUE THREAD

**Issue by zhangwenwu** [blueju/vue-g6-editor#1]
![image](https://user-images.githubusercontent.com/16423656/81911274-ab381580-95ff-11ea-8d1c-4f1f56a2385d.png)

**Comment by blueju** [comment]
没太理解，能发个GIF动图看一下吗？

**Comment by zhangwenwu** [comment]
![哈哈1](https://user-images.githubusercontent.com/16423656/81913638-d2dcad00-9602-11ea-9fe7-dbc989e59b65.gif)

**Comment by zhangwenwu** [comment]
好像图片都被强了。

**Comment by zhangwenwu** [comment]
就是 点上面的功能按钮，直接整个页面错乱，直接 用不了

**Comment by blueju** [comment]
线上demo试了下，好像不会。
刚才本地起了个，也不会。😅
不过之前貌似遇到过，你看下你那边的控制台里，是不是有两个 graph-container ？
![image](https://user-images.githubusercontent.com/49681036/81914733-429f6780-9604-11ea-8197-49e5c1f459db.png)

**Comment by zhangwenwu** [comment]
对，是这样。不过F12看到提示这个We're sorry but vue-g6-ediotr doesn't work properly without JavaScript enabled. Please enable it to continue

**Comment by zhangwenwu** [comment]
有空再上传一下源码吗，或者，

**Comment by blueju** [comment]
早上好，我刚想回复来着。
我最近这边没弄，所以没有新的修改，和github上的一样的。
刚刚也重新git pull了一份跑，还是没发现问题。
你方便详细写一下你的启动过程、用的是什么浏览器及版本信息吗？
或者最好能使用CodeSandbox重现一下并将链接分享上来。

**Comment by zhangwenwu** [comment]
就正常yarn install ，浏览器是谷歌最新，好几个都用过，行，我弄一下哈。

**Comment by zhangwenwu** [comment]
开发模式下会这样,我build之后的正常可以是使用的。~

**Comment by blueju** [comment]
不好意思，现在才回复你。

刚刚终于重现出错误了，我想这个应该就是你说的那个问题了，如下图：

![368d4859-50e7-4694-9f24-0429b5307d4a](https://user-images.githubusercontent.com/49681036/82135922-b5922380-983a-11ea-8ec5-955175a90704.gif)

我猜你应该是将 App.vue 中的 <cankao /> 给取消注释了。
我也是尝试将其取消注销后，才重现出的错误。

再者，也有我的锅，我只较重视了文档的编写，未重视代码（有点乱）。

稍后，我会重新整理一下代码，删除不必要的代码。

**Comment by zhangwenwu** [comment]
好的，，谢谢，就是我想做模型流程图，把左边的图片节点换成文字节点，拖过去还能显示文字，这个哪里有文档可以看吗 - -实在找不到

**Comment by blueju** [comment]
早上好~
你想要的是这种效果吗？
![c199ade3-f7ae-460c-8407-47ff9ccba58d](https://user-images.githubusercontent.com/49681036/82743794-ae22cb00-9da2-11ea-93cf-08a3fccab851.gif)
