### ISSUE TITLE
g6 editor配置项

### ISSUE THREAD

**Issue by antarcticxf** [blueju/vue-g6-editor#2]
你好，我最近在使用g6 editor，请问怎么在自定义节点中，让节点的宽度根据标签内容的长度自适应呢？

      // 注册模型卡片基类
      Flow.registerNode('model-card', {
        draw(item) {
          const group = item.getGraphicGroup();
          const model = item.getModel();
          const width = 184;
          const height = 40;
          const x = -184 / 2;
          const y = -height / 2;
          const borderRadius = 4;

          const keyShape = group.addShape('rect', {
            attrs: {
              x,
              y,
              width,
              height,
              radius: borderRadius,
              fill: 'white',
              stroke: '#CED4D9'
            }
          });

就是上面的width能根据名称文本的长度来自适应

非常感谢！

**Comment by blueju** [comment]
你好，关于节点宽度根据标签内容长度自适应的实现，我之前也找过相关资料，但貌似最后找到的答案只能是自己手动设置，没办法自适应。

**Comment by antarcticxf** [comment]
非常感谢！麻烦再请教一个问题，就是我在展示图的情况下，希望拖动的时候是整个图都能动，而单个节点的位置不能被拖拽，但同时又想hover、click节点的监听事件能保留。请问您有遇到过类似需求吗？有什么比较好的解决办法吗？

**Comment by blueju** [comment]
https://github.com/blueju/vue-g6-editor/issues/3
