### ISSUE TITLE
g6 editor画布上节点禁止拖拽改变位置，但同时保留节点的hover和click监听事件

### ISSUE THREAD

**Issue by antarcticxf** [blueju/vue-g6-editor#3]
您好，麻烦再请教一个问题，就是我在展示图的情况下，希望拖动的时候是整个图都能动，而单个节点的位置不能被拖拽，但同时又想hover、click节点的监听事件能保留。请问您有遇到过类似需求吗？有什么比较好的解决办法吗？

**Comment by blueju** [comment]
刚才简单看了下，暂未发现g6-editor有禁止节点拖拽的API或属性设置。

但或许能提供一点思路。

监听发生任何变化均会触发的事件 afterchange，如果数据模型 model 中的 x 和 y 发生改变，则调用 update，重新将 x 和 y 改回原来的值。

**Comment by antarcticxf** [comment]
好的，非常感谢！我试一下~

**Comment by blueju** [comment]
> 好的，非常感谢！我试一下~

您好，今天我试了下，貌似行不通，会死循环，不知道您实现了你希望的需求了吗？

**Comment by blueju** [comment]
> > 好的，非常感谢！我试一下~
> 
> 您好，今天我试了下，貌似行不通，会死循环，不知道您实现了你希望的需求了吗？

我现在是这么弄的，在 beforechange 事件中，通过throw主动抛出错误终止运行的方式，禁止编辑。

https://github.com/blueju/vue-g6-editor/tree/%233
