### ISSUE TITLE
老哥，流程图的布局  是不是还要结合antd加css才能实现官方文档图中的效果

### ISSUE THREAD

**Issue by xiano5** [blueju/vue-g6-editor#6]

**Comment by blueju** [comment]
图一：
![image](https://user-images.githubusercontent.com/49681036/85986138-5836e800-ba1e-11ea-806a-ecb5dd6df19b.png)

图二：
![image](https://user-images.githubusercontent.com/49681036/85986478-e6ab6980-ba1e-11ea-8c5f-3baf6fe3dcb6.png)

图三：
![image](https://user-images.githubusercontent.com/49681036/85986408-c5e31400-ba1e-11ea-9055-5372b46f504a.png)

从以上几个图来看，实现 g6-editor 的官方文档效果，应该的确是要结合 antd 加 css。
